
CREATE  TABLE IF NOT EXISTS DEVELOPERS(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS SKILLS(
  id INT AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE  IF NOT EXISTS DEVELOPER_SKILLS(
  developer_id INT NOT NULL,
  skill_id INT NOT NULL ,

  FOREIGN KEY (developer_id) REFERENCES developers(id),
  FOREIGN KEY (skill_id) REFERENCES skills(id)
);

CREATE TABLE IF NOT EXISTS PROJECTS(
  id int AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(100) not NULL
);

CREATE TABLE  IF NOT EXISTS DEVELOPER_PROJECTS(
  developer_id INT NOT NULL,
  PROJECT_ID INT NOT NULL ,

  FOREIGN KEY (developer_id) REFERENCES developers(id),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(id)
);

CREATE TABLE IF NOT EXISTS COMPANIES(
  id int AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(100) not NULL
);


CREATE TABLE  IF NOT EXISTS DEVELOPER_COMPANY(
  developer_id INT NOT NULL,
  company_id INT NOT NULL ,

  FOREIGN KEY (developer_id) REFERENCES developers(id),
  FOREIGN KEY (company_id) REFERENCES COMPANIES(id)
);


CREATE TABLE  IF NOT EXISTS DEVELOPER_PROJECTS(
  developer_id INT NOT NULL,
  PROJECT_ID INT NOT NULL ,

  FOREIGN KEY (developer_id) REFERENCES developers(id),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(id)
);


CREATE TABLE IF NOT EXISTS CUSTOMERS(
  id int AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) not NULL
);


CREATE TABLE  IF NOT EXISTS CUSTOMER_ORDERS(
  customer_id INT NOT NULL,
  PROJECT_ID INT NOT NULL ,
  Company_id INT NOT null,

  FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(id),
  FOREIGN KEY (Company_id) REFERENCES COMPANIES(id)
);


